apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nova
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm
      targetRevision: master
      path: nova
      helm:
        releaseName: nova
        valueFiles:
          - $values/argocd/openstack/values/services/nova.yaml
    - repoURL: https://github.com/daigo-suhara/capt-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://172.16.1.100:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm
      targetRevision: master
      path: cinder
      helm:
        releaseName: cinder
        valueFiles:
          - $values/argocd/openstack/values/services/cinder.yaml
    - repoURL: https://github.com/daigo-suhara/capt-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://172.16.1.100:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm
      targetRevision: master
      path: horizon
      helm:
        releaseName: horizon
        valueFiles:
          - $values/argocd/openstack/values/services/horizon.yaml
    - repoURL: https://github.com/daigo-suhara/capt-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://172.16.1.100:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
