labels:
  provisioner:
    node_selector_key: cluster-role
    node_selector_value: cp
  test:
    node_selector_key: cluster-role
    node_selector_value: cp

storageclass:
  csi_rbd:
    metadata:
      name: general
      default_storage_class: true
    provision_storage_class: true
    parameters:
      csi.storage.k8s.io/fstype: ext4
      csi.storage.k8s.io/provisioner-secret-name: pvc-ceph-conf-combined-storageclass
      csi.storage.k8s.io/provisioner-secret-namespace: ceph
      csi.storage.k8s.io/node-stage-secret-name: pvc-ceph-conf-combined-storageclass
      csi.storage.k8s.io/node-stage-secret-namespace: ceph
      csi.storage.k8s.io/controller-expand-secret-name: pvc-ceph-conf-combined-storageclass
      csi.storage.k8s.io/controller-expand-secret-namespace: ceph
      adminId: admin
      adminSecretName: pvc-ceph-conf-combined-storageclass
      adminSecretNamespace: ceph
      clusterID: ceph
      imageFeatures: layering
      imageFormat: "2"
      pool: rbd
      userId: admin
      userSecretName: pvc-ceph-client-key
