---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: tx1320-01
  namespace: tinkerbell
  labels:
    cluster-role: control-plane
spec:
  metadata:
    facility:
      facility_code: "home-lab"
    instance:
      id: "tx1320-01"
      hostname: "tx1320-01"
  interfaces:
    - netboot:
        allowPXE: true
      dhcp:
        arch: x86_64
        mac: "4c:52:62:16:33:8d"
        ip:
          address: "172.16.1.21"
          netmask: "255.255.255.0"
          gateway: "172.16.1.1"
          nameservers: ["8.8.8.8"]
  bmc:
    ip: "172.16.1.11"
    username: "admin"
    password: "admin"
---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: tx1320-02
  namespace: tinkerbell
  labels:
    cluster-role: worker
spec:
  metadata:
    facility:
      facility_code: "home-lab"
    instance:
      id: "tx1320-02"
      hostname: "tx1320-02"
  interfaces:
    - netboot:
        allowPXE: true
      dhcp:
        arch: x86_64
        mac: "4c:52:62:16:8b:9f"
        ip:
          address: "172.16.1.22"
          netmask: "255.255.255.0"
          gateway: "172.16.1.1"
          nameservers: ["8.8.8.8"]
  bmc:
    ip: "172.16.1.12"
    username: "admin"
    password: "admin"
---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: tx1320-03
  namespace: tinkerbell
  labels:
    cluster-role: worker
spec:
  metadata:
    facility:
      facility_code: "home-lab"
    instance:
      id: "tx1320-03"
      hostname: "tx1320-03"
  interfaces:
    - netboot:
        allowPXE: true
      dhcp:
        arch: x86_64
        mac: "4c:52:62:17:10:ef"
        ip:
          address: "172.16.1.23"
          netmask: "255.255.255.0"
          gateway: "172.16.1.1"
          nameservers: ["8.8.8.8"]
  bmc:
    ip: "172.16.1.13"
    username: "admin"
    password: "admin"
