apiVersion: bmc.tinkerbell.org/v1alpha1
kind: Machine
metadata:
  name: tx1320m3-01
  namespace: tinkerbell
spec:
  connection:
    host: 172.16.1.11
    port: 623
    insecureTLS: true
    authSecretRef:
      name: bmc-auth
      namespace: tinkerbell
    providerOptions:
      preferredOrder:
        - ipmitool
      ipmitool:
        port: 623
---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: tx1320m3-01
  namespace: tinkerbell
  labels:
    cluster-role: control-plane
spec:
  bmcRef:
    apiGroup: bmc.tinkerbell.org
    kind: Machine
    name: tx1320m3-01
  metadata:
    facility:
      facility_code: "home-lab"
    instance:
      id: "tx1320m3-01"
      hostname: "tx1320m3-01"
  interfaces:
    - dhcp:
        mac: "4c:52:62:16:33:8d"
