apiVersion: bmc.tinkerbell.org/v1alpha1
kind: Machine
metadata:
  name: tx1320m3-03
  namespace: tinkerbell
spec:
  connection:
    host: 172.16.1.13
    authSecretRef:
      name: bmc-auth
      namespace: tinkerbell
    insecureTLS: true
---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: tx1320m3-03
  namespace: tinkerbell
  labels:
    cluster-role: control-plane
spec:
  bmcRef:
    apiGroup: bmc.tinkerbell.org
    kind: Machine
    name: tx1320m3-03
  metadata:
    instance:
      id: "4c:52:62:17:10:ef"
      hostname: "tx1320m3-03"
  interfaces:
    - dhcp:
        uefi: true
        mac: "4c:52:62:17:10:ef"
        ip:
          address: 172.16.10.13
          gateway: 172.16.0.1
          netmask: 255.255.0.0
        name_servers:
          - 1.1.1.1
          - 8.8.8.8
      disableDhcp: false
      netboot:
        allowPXE: true
        allowWorkflow: true
  disks:
    - device: /dev/sda
