apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: tx1320m3-03
  namespace: tinkerbell
spec:
  metadata:
    facility:
      facility_code: "home-lab"
    instance:
      id: "tx1320m3-03"
      hostname: "tx1320m3-03"
  interfaces:
    - dhcp:
        mac: "4c:52:62:17:10:ef"
