apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: metallb-config-reconcile
  namespace: tinkerbell
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: cluster
  strategy: Reconcile
  resources:
    - name: metallb-config-manifest
      kind: Secret
