apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: work-cluster-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.16.1.110-172.16.1.199
  autoAssign: true
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: work-cluster-bgp
  namespace: metallb-system
spec:
  ipAddressPools:
    - work-cluster-pool
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: rtx1200
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64513
  peerAddress: 172.16.0.1
