apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: work-cluster-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.16.0.0/16
  autoAssign: true
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: work-cluster-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - work-cluster-pool
---
