apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2026.5.2
    helm:
      values: |
        authentik:
          secret_key: "dcloud-authentik-secret-key-please-change"
          bootstrap_password: "dcloud-authentik-bootstrap-password-please-change"
          bootstrap_token: "dcloud-authentik-bootstrap-token-please-change"
          error_reporting:
            enabled: false
          postgresql:
            password: "dcloud-authentik-postgres-password-please-change"
        server:
          ingress:
            enabled: true
            hosts:
              - auth.daigo-suhara.com
        postgresql:
          enabled: true
          auth:
            password: "dcloud-authentik-postgres-password-please-change"
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
