apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  ignoreDifferences:
    - group: serving.knative.dev
      kind: Service
      name: container
      namespace: dcloud-system
      jsonPointers:
        - /spec/template/spec/containers/0/ports/0/protocol
        - /spec/template/spec/containers/0/readinessProbe/successThreshold
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/enableServiceLinks
        - /spec/template/spec/timeoutSeconds
  source:
    repoURL: https://github.com/daigo-suhara/dcloud.git
    targetRevision: main
    path: charts/dcloud
    helm:
      releaseName: dcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: dcloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
