apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: master
    path: cluster/argocd/istio-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: istio-ingressgateway
      namespace: istio-system
      jqPathExpressions:
        - .spec.template.spec.containers[].image
        - .spec.template.spec.containers[].env
        - .spec.template.spec.containers[].volumeMounts
        - .spec.template.spec.volumes
        - .spec.template.spec.initContainers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
