apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving-core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: master
    path: cluster/argocd/knative-serving/core
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
