apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - knative-serving-crds.yaml
  - knative-serving-core.yaml
  - cloudflared.yaml
  - rook-ceph
  - dcp.yaml
