apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-cm.yaml
  - sealed-secrets.yaml
  - istio-base.yaml
  - istiod.yaml
  - istio.yaml
  - knative-serving-crds.yaml
  - knative-serving-core.yaml
  - net-istio.yaml
  - dcloud.yaml
  - cloudflared.yaml
  - rook-ceph
