---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dcloud-database
  namespace: dcloud-system
spec:
  encryptedData:
    DCLD_DATABASE_URL: AgCbMrf28o5KmwSnkhVOScHy8iZxpK8aQibsjyS/ffbtxtPF+6Z2Yw7Q4quDxvY2b4zrBi7qgjo3HMrOZoDbcVAgfqsB9VwyHG7kys6XJqPUTRDY1wmgE6ndeY7lt5Lq6/Gm/dFOxOvJLL++o0DZ/g9tlCwmfybjvJvZkKVWHiBIX0hUndReU7HSbuzbgvDEZh7Xmf05VSx9gx3+qUHc0v9xP5ox9/RrpYtOOiPSd0ATQPvQv1ocGLpthePasdl3sj/t+iXi+8QrylPpnQraccHP6tPUb/SymjLYKmhguNAffhdbc99Cq0P+VemwjycLOdjkhpO3YRx8yOKL3nPNYa0dzJb3UHt54zdRd7BX5C99rnaX0dJOABBEg0rwozKGkvbcc7wBjcUUqCjjlqOQ8e0FVeCl1aE0+G7psjIG/Ox0NezY22ay3ouVSs8F4AeekYadSTb5dmmVqT1k6FfA0mUIKgvittj6B3yz6FYzxoD11/aThd5v2wMVq4Q+PmZLqjRYLS8INaDlWgoRyiTPk/GvKBY+koR0D8Ou+o2dHtmBCp3+yBN8NVFo7KiH+fE2AjaZ95qy0J8sbc/4r+t97Je+r706UwQhGAmXvIEYVEgBSpZSEgIK3aSLV+UjdUxkeAfzjJGTIvjcvdy858D6nYKI4jlLnA35yZmgwRk0wF9Bx+SJhvrbN/Bfq7/Tg/D+2ANYzDS45q4F5BBDoOGz44ZNyAgeNglzd4P6/gNcS4CUB/QRvHRi1YtpqsDEfW2q7p4N6YVVM0acRymJ2pdCdwl5LFHMLY0URtBB6rzBPH8j33lsLJz1kV9kMt9he8Xmm/IudtJWwc+gnklqZdxI9+KPkRk=
  template:
    metadata:
      name: dcloud-database
      namespace: dcloud-system
