apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: openstack-cinder
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: cinder
    targetRevision: master
    helm:
      releaseName: cinder
      valuesObject:
        conf:
          cinder:
            DEFAULT:
              enabled_backends: rbd1
            rbd1:
              volume_driver: cinder.volume.drivers.rbd.RBDDriver
              volume_backend_name: rbd1
              rbd_pool: volumes
  destination:
    name: tinkerbell
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
