apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: openstack-placement
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: placement
    targetRevision: master
    helm:
      releaseName: placement
  destination:
    name: tinkerbell
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
