apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: openstack-ceph-adapter-rook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: ceph-adapter-rook
    targetRevision: master
    helm:
      releaseName: ceph-adapter-rook
      valuesObject:
        endpoints:
          ceph_mon:
            namespace: rook-ceph
  destination:
    name: tinkerbell
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
