apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: openstack-neutron
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm.git
    path: neutron
    targetRevision: master
    helm:
      releaseName: neutron
  destination:
    server: https://172.16.1.100:6443
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
