apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - namespace-ceph.yaml
  - app-ceph-adapter-rook.yaml
  - app-mariadb.yaml
  - app-rabbitmq.yaml
  - app-memcached.yaml
  - app-keystone.yaml
  - app-glance.yaml
  - app-placement.yaml
  - app-openvswitch.yaml
  - app-libvirt.yaml
  - app-neutron.yaml
  - app-nova.yaml
  - app-cinder.yaml
  - app-horizon.yaml
