apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: control-plane
  namespace: tinkerbell
spec:
  replicas: 3
  version: v1.35.4
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TinkerbellMachineTemplate
        name: control-plane
  rollout:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
  kubeadmConfigSpec:
    format: cloud-config
    ntp:
      enabled: true
      ntp_client: chrony
      servers:
        - ntp.nict.jp
        - pool.ntp.org
    preKubeadmCommands:
      - mkdir -p /etc/kubernetes/manifests
      - ctr images pull ghcr.io/kube-vip/kube-vip:v1.0.0
      - >-
        ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v1.0.0 vip /kube-vip manifest pod --arp --interface "$(ip -4 route list default | awk '{print $5; exit}')" --address 172.16.1.100 --controlplane --leaderElection | sed 's|path: /etc/kubernetes/admin.conf|path: /etc/kubernetes/super-admin.conf|g' > /etc/kubernetes/manifests/kube-vip.yaml
    clusterConfiguration:
      apiServer:
        certSANs:
          - 172.16.1.100
          - 127.0.0.1
      controllerManager:
        extraArgs:
          - name: enable-hostpath-provisioner
            value: "true"
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.hostname }}'
        kubeletExtraArgs:
          - name: provider-id
            value: 'tinkerbell://tinkerbell/{{ ds.meta_data.hostname }}'
          - name: node-labels
            value: 'cluster-role=control-plane,openstack-control-plane=enabled'
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.hostname }}'
        kubeletExtraArgs:
          - name: provider-id
            value: 'tinkerbell://tinkerbell/{{ ds.meta_data.hostname }}'
          - name: node-labels
            value: 'cluster-role=control-plane,openstack-control-plane=enabled'
    postKubeadmCommands:
      - kubectl --kubeconfig /etc/kubernetes/admin.conf taint nodes --all node-role.kubernetes.io/control-plane-
    users:
      - name: tinkerbell
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        sshAuthorizedKeys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+3Q/eAOgoIs0pNtGvQ8ueXK1Gg8CnIdhcU9rwpeMFm suharadaigo"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
  name: control-plane
  namespace: tinkerbell
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  template:
    spec:
      bootOptions:
        bootMode: netboot
      hardwareAffinity:
        required:
          - labelSelector:
              matchLabels:
                cluster-role: control-plane
