apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: control-plane
  namespace: tinkerbell
spec:
  replicas: 3
  version: v1.35.4
  machineTemplate:
    metadata: {}
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: TinkerbellMachineTemplate
      name: control-plane
      namespace: tinkerbell
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  kubeadmConfigSpec:
    format: cloud-config
    preKubeadmCommands:
      - mkdir -p /etc/kubernetes/manifests
      - ctr images pull ghcr.io/kube-vip/kube-vip:v1.0.0
      - ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v1.0.0 vip /kube-vip manifest pod --arp --interface "$(ip -4 route list default | awk '{print $5; exit}')" --address 172.16.1.100 --controlplane --leaderElection > /etc/kubernetes/manifests/kube-vip.yaml
    clusterConfiguration:
      apiServer:
        certSANs:
          - 172.16.1.100
          - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
      dns: {}
      etcd: {}
      networking: {}
      scheduler: {}
    users:
      - name: tinkerbell
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        sshAuthorizedKeys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+3Q/eAOgoIs0pNtGvQ8ueXK1Gg8CnIdhcU9rwpeMFm suharadaigo"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
  name: control-plane
  namespace: tinkerbell
spec:
  template:
    spec:
      bootOptions:
        bootMode: netboot
      hardwareAffinity:
        required:
          - labelSelector:
              matchLabels:
                cluster-role: control-plane
      templateOverride: |
        version: "0.1"
        name: {{.Name}}
        global_timeout: 6000
        tasks:
          - name: "{{.Name}}"
            worker: "{{.device_1}}"
            volumes:
              - /dev:/dev
              - /dev/console:/dev/console
              - /lib/firmware:/lib/firmware:ro
            actions:
              - name: "stream image"
                image: quay.io/tinkerbell/actions/oci2disk
                timeout: 600
                environment:
                  IMG_URL: ghcr.io/tinkerbell/cluster-api-provider-tinkerbell/ubuntu:2404-v1.35.4-amd64.gz
                  DEST_DISK: {{ index .Hardware.Disks 0 }}
                  COMPRESSED: true
              - name: "add tink cloud-init config"
                image: quay.io/tinkerbell/actions/writefile
                timeout: 90
                environment:
                  DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
                  FS_TYPE: ext4
                  DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
                  UID: 0
                  GID: 0
                  MODE: 0600
                  DIRMODE: 0700
                  CONTENTS: |
                    datasource:
                      Ec2:
                        metadata_urls: ["http://172.16.1.10:50061"]
                        strict_id: false
                    system_info:
                      default_user:
                        name: tink
                        groups: [wheel, adm]
                        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                        shell: /bin/bash
                    manage_etc_hosts: localhost
                    warnings:
                      dsid_missing_source: off
              - name: "add tink cloud-init ds-config"
                image: quay.io/tinkerbell/actions/writefile
                timeout: 90
                environment:
                  DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
                  FS_TYPE: ext4
                  DEST_PATH: /etc/cloud/ds-identify.cfg
                  UID: 0
                  GID: 0
                  MODE: 0600
                  DIRMODE: 0700
                  CONTENTS: |
                    datasource: Ec2
              - name: "kexec image"
                image: ghcr.io/jacobweinstock/waitdaemon:latest
                timeout: 90
                pid: host
                environment:
                  BLOCK_DEVICE: {{ formatPartition ( index .Hardware.Disks 0 ) 1 }}
                  FS_TYPE: vfat
                  IMAGE: quay.io/tinkerbell/actions/kexec
                  WAIT_SECONDS: 5
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
