apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - control-plane.yaml
  - worker.yaml
  - provisioning-template.yaml
  - addons/helmchartproxy-cilium.yaml
  - addons/helmchartproxy-metallb.yaml
  - addons/helmchartproxy-argocd.yaml
  - addons/crs-metallb-config.yaml
  - addons/crs-workload-argocd-app.yaml

secretGenerator:
  - name: metallb-config-manifest
    namespace: tinkerbell
    type: addons.cluster.x-k8s.io/resource-set
    files:
      - addons/metallb-config.yaml
  - name: workload-argocd-app-manifest
    namespace: tinkerbell
    type: addons.cluster.x-k8s.io/resource-set
    files:
      - addons/workload-argocd-app.yaml

generatorOptions:
  disableNameSuffixHash: true
