apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - control-plane.yaml
  - workers.yaml
  - provisioning-template.yaml
  - addons/crs-cilium.yaml

secretGenerator:
  - name: cilium-manifest
    namespace: tinkerbell
    files:
      - addons/cilium.yaml
generatorOptions:
  disableNameSuffixHash: true

