apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - cp.yaml
  - workers.yaml
  - provisioning-template.yaml
  - addons/crs-cilium.yaml

secretGenerator:
  - name: cilium-manifest
    namespace: tinkerbell
    type: addons.cluster.x-k8s.io/resource-set
    files:
      - addons/cilium.yaml
generatorOptions:
  disableNameSuffixHash: true

