apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: cluster-provisioning-template
  namespace: tinkerbell
spec:
  data: |
    version: "0.1"
    name: cluster-provisioning-template
    global_timeout: 6000
    tasks:
      - name: "cluster-provisioning-template"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
        actions:
          - name: "stream image"
            image: quay.io/tinkerbell/actions/oci2disk
            timeout: 1200
            environment:
              IMG_URL: ghcr.io/tinkerbell/cluster-api-provider-tinkerbell/ubuntu:2404-v1.35.4-amd64.gz
              DEST_DISK: {{ index .Hardware.Disks 0 }}
              COMPRESSED: true
          - name: "add tink cloud-init config"
            image: quay.io/tinkerbell/actions/writefile
            timeout: 90
            environment:
              DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource:
                  Ec2:
                    metadata_urls: ["http://{{ .tootles_ip_port }}"]
                    strict_id: false
                system_info:
                  default_user:
                    name: tink
                    groups: [wheel, adm]
                    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                    shell: /bin/bash
                manage_etc_hosts: localhost
                warnings:
                  dsid_missing_source: off
          - name: "add tink cloud-init ds-config"
            image: quay.io/tinkerbell/actions/writefile
            timeout: 90
            environment:
              DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/ds-identify.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource: Ec2
          - name: "kexec image"
            image: ghcr.io/jacobweinstock/waitdaemon:0.2.1
            timeout: 90
            pid: host
            environment:
              BLOCK_DEVICE: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
              FS_TYPE: ext4
              IMAGE: quay.io/tinkerbell/actions/kexec
              WAIT_SECONDS: 5
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
