apiVersion: tinkerbell.org/v1alpha1
kind: Template
metadata:
  name: cluster-provisioning-template
  namespace: tinkerbell
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  data: |
    version: "0.1"
    name: cluster-provisioning-template
    global_timeout: 6000
    tasks:
      - name: "cluster-provisioning-template"
        worker: "{{.device_1}}"
        volumes:
          - /dev:/dev
        actions:
          - name: "stream image"
            image: quay.io/tinkerbell/actions/oci2disk
            timeout: 1200
            environment:
              IMG_URL: ghcr.io/tinkerbell/cluster-api-provider-tinkerbell/ubuntu:2404-v1.35.4-amd64.gz
              DEST_DISK: {{ index .Hardware.Disks 0 }}
              COMPRESSED: true
          - name: "add tink cloud-init config"
            image: quay.io/tinkerbell/actions/writefile
            timeout: 90
            environment:
              DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                hostname: {{.Hardware.Name}}
                preserve_hostname: false
                datasource:
                  Ec2:
                    metadata_urls: ["http://172.16.0.10:7172"]
                    strict_id: false
                system_info:
                  default_user:
                    name: tinkerbell
                    groups: [wheel, adm]
                    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                    shell: /bin/bash
                manage_etc_hosts: localhost
                warnings:
                  dsid_missing_source: off
          - name: "add tink cloud-init ds-config"
            image: quay.io/tinkerbell/actions/writefile
            timeout: 90
            environment:
              DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
              FS_TYPE: ext4
              DEST_PATH: /etc/cloud/ds-identify.cfg
              UID: 0
              GID: 0
              MODE: 0600
              DIRMODE: 0700
              CONTENTS: |
                datasource: Ec2
          - name: "write netplan config"
            image: quay.io/tinkerbell/actions/writefile
            timeout: 90
            environment:
              DEST_DISK: {{ formatPartition ( index .Hardware.Disks 0 ) 3 }}
              FS_TYPE: ext4
              DEST_PATH: /etc/netplan/50-tinkerbell.yaml
              UID: 0
              GID: 0
              MODE: 0644
              DIRMODE: 0755
              CONTENTS: |
                network:
                  version: 2
                  renderer: networkd
                  ethernets:
                    eno1:
                      addresses: ["{{ (index .Hardware.Interfaces 0).DHCP.IP.Address }}/16"]
                      routes:
                        - to: default
                          via: "{{ (index .Hardware.Interfaces 0).DHCP.IP.Gateway }}"
                      nameservers:
                        addresses:
                          - 8.8.8.8
                      link-local: [ipv4]
                      dhcp4: false
                      dhcp6: false
                      accept-ra: false
                      optional: true
          - name: "reboot"
            image: alpine:3
            timeout: 90
            pid: host
            command: ["chroot", "/proc/1/root", "reboot"]
