apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: HEAD
    path: cluster/argocd/rook/storageclass
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
