apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: 1.19.4
      helm:
        releaseName: rook-ceph-cluster
        valueFiles:
          - $values/cluster/argocd/rook/values/rook-cluster.yaml
    - repoURL: https://github.com/daigo-suhara/capt-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
