apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-horizon
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: default
  source:
    repoURL: https://github.com/openstack/openstack-helm.git
    path: horizon
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
