apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-keystone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: keystone
    targetRevision: master
    helm:
      values: |
        manifests:
          job_db_init: true
          job_db_sync: true
          job_ks_user: true
          job_ks_service: true
          job_ks_endpoints: true
          job_bootstrap: true
          job_credential_setup: true
          job_fernet_setup: true
          secret_keystone_db_admin: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
