apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-keystone
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://github.com/openstack/openstack-helm.git
    path: keystone
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
