apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/openstack.yaml
  - apps/ceph-mon.yaml
  - apps/ceph-osd.yaml
  - apps/ceph-client.yaml
  - apps/ceph-provisioners.yaml
  - apps/mariadb.yaml
  - apps/rabbitmq.yaml
  - apps/memcached.yaml
  - apps/openvswitch.yaml
  - apps/libvirt.yaml
  - apps/keystone.yaml
  - apps/placement.yaml
  - apps/glance.yaml
  - apps/neutron.yaml
  - apps/nova.yaml
  - apps/cinder.yaml
  - apps/horizon.yaml
