apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openstack-namespace.yaml
  - mariadb.yaml
  - rabbitmq.yaml
  - memcached.yaml
  - libvirt.yaml
  - openvswitch.yaml
  - keystone.yaml
  - glance.yaml
  - placement.yaml
  - nova.yaml
  - neutron.yaml
  - horizon.yaml
