apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-libvirt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra
    chart: libvirt
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
