apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-mariadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/openstack/openstack-helm-infra.git
    path: mariadb
    targetRevision: master
    helm:
      values: |
        pod:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
