apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-mariadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: mariadb
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        helm3_hook: false
        pod:
          replicas:
            server: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
