apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-neutron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm
    chart: neutron
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
