apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-neutron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: neutron
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        helm3_hook: false
        manifests:
          ingress_api: false
          job_db_init: true
          job_db_sync: true
          job_ks_user: true
          job_ks_service: true
        conf:
          neutron:
            DEFAULT:
              l3_ha: false
              max_l3_agents_per_router: 1
        endpoints:
          oslo_messaging:
            host_fqdn_override:
              default: rabbitmq.openstack.svc.cluster.local
          auto_bridge_add:
            br-ex: eno1
          plugins:
            ml2_conf:
              ml2_type_flat:
                flat_networks: public
            openvswitch_agent:
              ovs:
                bridge_mappings: public:br-ex
        extraObjects:
          - apiVersion: v1
            kind: Service
            metadata:
              name: neutron-public
            spec:
              type: LoadBalancer
              loadBalancerIP: 172.16.100.14
              externalTrafficPolicy: Cluster
              ports:
                - name: q-api
                  port: 9696
                  protocol: TCP
                  targetPort: 9696
              selector:
                app.kubernetes.io/component: server
                app.kubernetes.io/instance: openstack-neutron
                app.kubernetes.io/name: neutron
                application: neutron
                component: server
                release_group: openstack-neutron
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
