apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-nova
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: nova
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        helm3_hook: false
        manifests:
          job_db_init: true
          job_db_sync: true
          job_ks_user: true
          job_ks_service: true
        conf:
          nova:
            libvirt:
              virt_type: kvm
              images_type: rbd
              images_rbd_pool: vms
              images_rbd_ceph_conf: /etc/ceph/ceph.conf
              rbd_user: nova
              rbd_secret_uuid: 457f605d-adaa-4710-83b9-331487137b01 # Placeholder
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
