apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-nova
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: nova
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        helm3_hook: false
        manifests:
          job_db_init: true
          job_db_sync: true
          job_ks_user: true
          job_ks_service: true
          job_storage_init: false
          service_ingress_metadata: true
          service_ingress_novncproxy: true
          service_ingress_osapi: true
          service_ingress_serialproxy: true
          service_ingress_spiceproxy: true
        conf:
          ceph:
            enabled: true
            cinder:
              user: cinder
              keyring: AQCEawxqDbU8GBAAisYBswfj/NG2mG9dS7irGA==
          nova:
            DEFAULT:
              transport_url: rabbit://nova:password@rabbitmq.openstack.svc.cluster.local:5672/nova
            keystone_authtoken:
              username: nova
              password: password
              project_name: service
              user_domain_name: service
              project_domain_name: service
            service_user:
              username: nova_service_user
              password: password
              project_name: service
              user_domain_name: service
              project_domain_name: service
            libvirt:
              virt_type: kvm
              images_type: rbd
              images_rbd_pool: vms
              images_rbd_ceph_conf: /etc/ceph/ceph.conf
              rbd_user: cinder
              rbd_secret_uuid: 457eb676-33da-42ec-9a8c-9293d545c337
            vnc:
              novncproxy_base_url: http://172.16.100.14/vnc_auto.html
        endpoints:
          oslo_messaging:
            host_fqdn_override:
              default: rabbitmq.openstack.svc.cluster.local
        extraObjects:
          - apiVersion: batch/v1
            kind: Job
            metadata:
              name: nova-ks-endpoints-fix
            spec:
              backoffLimit: 0
              template:
                spec:
                  restartPolicy: Never
                  containers:
                    - name: fix-endpoint
                      image: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble
                      command:
                        - /bin/sh
                        - -ec
                        - |
                          export OS_AUTH_URL=http://keystone-api.openstack.svc.cluster.local:5000/v3
                          export OS_USERNAME=admin
                          export OS_PASSWORD=password
                          export OS_PROJECT_NAME=admin
                          export OS_USER_DOMAIN_NAME=Default
                          export OS_PROJECT_DOMAIN_NAME=Default
                          export OS_INTERFACE=internal
                          endpoint_id=$(/var/lib/openstack/bin/openstack endpoint list --service nova --interface public -f value -c ID)
                          /var/lib/openstack/bin/openstack endpoint set --url http://nova-api.openstack.svc.cluster.local:8774/v2.1/ "$endpoint_id"
          - apiVersion: gateway.networking.k8s.io/v1
            kind: Gateway
            metadata:
              name: novncproxy-gateway
            spec:
              gatewayClassName: cilium
              addresses:
                - type: IPAddress
                  value: 172.16.100.14
              listeners:
                - name: http
                  port: 80
                  protocol: HTTP
                  allowedRoutes:
                    namespaces:
                      from: Same
          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: novncproxy-route
            spec:
              parentRefs:
                - name: novncproxy-gateway
                  group: gateway.networking.k8s.io
                  kind: Gateway
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - group: ""
                      kind: Service
                      name: nova-novncproxy
                      port: 6080
                      weight: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
