apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-openvswitch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: openvswitch
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
