apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-placement
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: placement
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        helm3_hook: false
        manifests:
          ingress_api: false
          job_db_init: true
          job_db_sync: true
          job_ks_user: true
          job_ks_service: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
