apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://tarballs.opendev.org/openstack/openstack-helm-infra
    chart: rabbitmq
    targetRevision: 0.1.0
    helm:
      values: |
        pod:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
