apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: rabbitmq
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        helm3_hook: false
        pod:
          replicas:
            server: 1
        manifests:
          ingress_management: false
          service_ingress_management: false
        extraObjects:
          - apiVersion: v1
            kind: Service
            metadata:
              name: rabbitmq-public
            spec:
              type: LoadBalancer
              loadBalancerIP: 172.16.100.12
              selector:
                app.kubernetes.io/component: server
                app.kubernetes.io/instance: openstack-rabbitmq
                app.kubernetes.io/name: rabbitmq
                application: rabbitmq
                component: server
                release_group: openstack-rabbitmq
              ports:
                - name: http
                  port: 15672
                  protocol: TCP
                  targetPort: 15672
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/configmap-etc-hash
        - /metadata/annotations/configmap-bin-hash
