labels:
  agent:
    compute:
      node_selector_key: cluster-role
      node_selector_value: control-plane
    compute_ironic:
      node_selector_key: cluster-role
      node_selector_value: control-plane
  api_metadata:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  conductor:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  job:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  novncproxy:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  osapi:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  scheduler:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  serialproxy:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  spiceproxy:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  test:
    node_selector_key: cluster-role
    node_selector_value: control-plane

rbd_pool:
  app_name: nova-vms
  chunk_size: 8
  crush_rule: replicated_rule
  replication: 3
