apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    ingress:
      - hostname: argo.daigo-suhara.com
        service: https://172.16.100.10
        originRequest:
          noTLSVerify: true
      - hostname: cloud.daigo-suhara.com
        service: http://dcloud-console.dcloud-system.svc.cluster.local:8080
      - hostname: "*.drkatana.com"
        service: http://kourier.kourier-system.svc.cluster.local:80
      - service: http_status:404
