apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCYb53GMWgkNe6xBQqq2mduMdrz96MCXPmk+sHzozrKsjgYmjrgsFovYu/Fcg/jj0RTM9tXvUc66miH/xOGzjrn8c0T3Hud3fR962KebXXLClnA3QyAKAZSQYr3M4DxITgXvr4nQQC1YFZn5WE00FnSZb9NqZqUj1aXF4Ogg178EE0+QxtTFZ4EaqeBpl9xJvsQ9qJ5tj3Cj9N5tHCRaWopBru0TO9F9VfsFHWV1T0Qpy6bcHgT3qFKLloLlfP3l71yfHbIJ4i4M/ptCfWjq1nlS9vyiOaWbm0rQrogiZVc2Und999ersxMfZa5xo8DwZT2HErLxLU+yp9fFxNy9NAzGT8nN7exTwq++svDaDFj1N0OSbFECUjv+RumFNCPhKqwQYf/yJV+D0qaGetdBhe/EvFe62JTEm+iTZ/Npr3x90vkXDAhP9lqQC5wCgmc9e7MHpSIKPjdJx1GkUXw7hC3ra1uu4+IbXM0HO3hs/TnPear9tKjhE1g9qF17wtXao+J/gbVWHCDbu9sNWBxDCMpw8f4oJv17l5hFTZeM7YkaNsmT64ljqBBzivpEhmimxoO6XXqcdlNhuIXZtNaXMN4j6Q9LkXcKDkqSkZ2B6p8IL4GqvDK6aqDPR8VZqw1+0KVfSUqMjZxGlWK7+4BW9S3P8ZHUMQ2lndH4a0g9wPpHgmgQOa/zE8q/j5QRIM75p0zBUHrZD3tMYkIk9C09zc+M3JQoOHWa4iq09nQpzRkC+DIMZFE3NlNf6JMlQk0op+bWEx7iz66KDra/RF7BbyiruOCreCalW+9FavU1aluTZKCmsbnGfIg7WZPmsee5uSkBgbPWJ2PxWy5DaZhKeAOoyXlw8Wg3669xNDfHqO2FRBMys41N2HlPJXGn3Rs78xxxzvA/4P7LWDCg9zO8F4s+ZbH4HhkuJjP2zg8bmgHl4fu0LSVY5rQ
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare
