apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBxwIrAKCmzqfIhZbPUngl+BYIEKoxP3SIRSgvGkTQaH/DV06vG0rHYGPN6aAAPbkZloGlh5yGoH7mScEinK1a8zTqDo+MCI+KsvswTqQYikhjVu4+tZ6TEEJVJmWEt2Zen6wD+ZilAjLxD2SSqdxLDxA/KirqXxLcDLTCCQTC+BGsjRPTbSVLhK7X+EnJqrwKhsqP2ZqjWbhGwYwBl8TKyQQOIY9MIBWox53YA+jzSu+jM7d5X2LjmGRO1638bI/mBg+v6gnZRVRgRVUp9GPP6a6ZyQAk0o0uqG+HHP/oat0OAS4Pru67Jrc8Qa79KuvFvjjYwi1PBNYkzoEdQ+yXrMNcfh5ufPfwJS/86A4Ey8WkarO3EOQWnURS5RaPNrIH4KSTw/uI/0idJ7+yy1IVMjL9wtoCdFvXnNJqRjhPZ9a/r5L1TMS2gHT4pXvUMAD7SYxWL1M9Itc5bJnR+ivQGQRlAAmcSeporq71HEEBr0pO6A8KXgiLeJnXWPjfAnreCirlM07xBRXwYQBZPVdSoj9v+3fDvKoNfbpUXvLk32S/4qhTWRW2g1iCmjuOY6mKsz57dgzlAECBArKS+WVGmpO+puWv1yczMvmfM7ZTIy7IVU7ipsj8AEt886LPcyFj87Z3Wt4zmz7lsRWdTyU6d0DU+9Hztpg9EiZdCr4FJHtJApe3b7NicJY2PMEappQqAL4YKr46uKxlOAePhXRttkHZk4L0EFBlfXTIgIoLpBadSFsYg9QbO5/WzUhRTM2N28EZ6Sv2786kjdYHg/gIzbQJ3GuIXeQqgylRO90+hGbgqMvK3i/RPln2gQ1t6rBhd12w+sKTTXjYrunL0AIoaIdym86FNHxTulpY7HgPWFxiEe2enpNjGFOUC63ob8odHOUYrF5b5e8qsM67Mm6WndBqXVqpnVHyLcv/dtnmyi6pmr+Bfoukf
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare
    type: Opaque
