apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinkerbell
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: HEAD
    path: system/tinkerbell-chart/stack
    helm:
      values: |
        stack:
          interface: eno1
          loadBalancerIP: 172.16.1.10
        hegel:
          trustedProxies: [10.0.0.0/8]
        nginx:
          resolver: kube-dns.kube-system.svc.cluster.local
  destination:
    server: https://kubernetes.default.svc
    namespace: tinkerbell
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
