apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: master
    path: system/capt
  destination:
    server: https://kubernetes.default.svc
    namespace: capi-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
