apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinkerbell
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/tinkerbell/charts/tinkerbell
    path: .
    targetRevision: v0.22.1
    helm:
      values: |
        deployment:
          strategy:
            type: Recreate
          hostNetwork: true
          envs:
            smee:
              dhcpBindInterface: enx00e04c247a98
        artifactsFileServer: http://172.16.0.10:7173
  destination:
    server: https://kubernetes.default.svc
    namespace: tinkerbell
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      namespace: tinkerbell
      name: hook-artifacts
      jsonPointers:
        - /spec/volumeName
