apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: metallb-config
  namespace: argocd
spec:
  project: default
  source:
    path: metallb
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: HEAD
  destination:
    name: tinkerbell
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
