apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinkerbell
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/tinkerbell/charts
    chart: tinkerbell
    targetRevision: v0.22.1
    helm:
      values: |
        trustedProxies: "10.0.0.0/8"
        publicIP: 192.0.2.116
        artifactsFileServer: http://192.0.2.117:7173
  destination:
    server: https://kubernetes.default.svc
    namespace: tinkerbell
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
