apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: system/capi-operator
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: capi-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
