apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caaph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    path: system/caaph
    repoURL: https://github.com/daigo-suhara/capt-cluster.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: caaph-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
