apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-capi-operator.yaml
  - app-cert-manager.yaml
  - app-tinkerbell.yaml
  - app-capt.yaml
  - app-hardware.yaml
  - app-cluster.yaml
  - app-metallb.yaml
  - app-metallb-config.yaml
  - app-rook-ceph-operator.yaml
  - app-rook-ceph-cluster.yaml
  - app-openstack-helm.yaml
