apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-capi-operator.yaml
  - app-cert-manager.yaml
  - app-caaph.yaml
  - app-tinkerbell.yaml
  - app-capt.yaml
  - app-hardware.yaml
  - app-cluster.yaml
  - app-kubevirt.yaml
