apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tinkerbell
resources:
  - stack.yaml
  # CRDを追加
  - https://raw.githubusercontent.com/tinkerbell/tink/main/config/crd/bases/tinkerbell.org_hardware.yaml
  - https://raw.githubusercontent.com/tinkerbell/tink/main/config/crd/bases/tinkerbell.org_templates.yaml
  - https://raw.githubusercontent.com/tinkerbell/tink/main/config/crd/bases/tinkerbell.org_workflows.yaml
  - https://raw.githubusercontent.com/tinkerbell/rufio/main/config/crd/bases/bmc.tinkerbell.org_machines.yaml
  - https://raw.githubusercontent.com/tinkerbell/rufio/main/config/crd/bases/bmc.tinkerbell.org_tasks.yaml
  - https://raw.githubusercontent.com/tinkerbell/rufio/main/config/crd/bases/bmc.tinkerbell.org_jobs.yaml
