labels:
  api:
    node_selector_key: cluster-role
    node_selector_value: cp
  job:
    node_selector_key: cluster-role
    node_selector_value: cp
  test:
    node_selector_key: cluster-role
    node_selector_value: cp
storage: pvc
volume:
  class_name: general
  size: 10Gi
