apiVersion: batch/v1
kind: Job
metadata:
  name: placement-ks-endpoints
  namespace: openstack
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: placement-ks-endpoints
          image: quay.io/airshipit/openstack-client:2026.1-ubuntu_noble
          command:
            - /bin/sh
            - -c
            - exit 0
