labels:
  mon:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  mgr:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  job:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  test:
    node_selector_key: cluster-role
    node_selector_value: control-plane
network:
  public: 172.16.0.0/16
  cluster: 172.16.0.0/16
