labels:
  osd:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  job:
    node_selector_key: cluster-role
    node_selector_value: control-plane
  test:
    node_selector_key: cluster-role
    node_selector_value: control-plane
conf:
  storage:
    osd:
      - data:
          type: directory
          location: /var/lib/openstack-helm/ceph/osd/osd-one
        journal:
          type: directory
          location: /var/lib/openstack-helm/ceph/osd/journal-one
