apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-operator
  namespace: capi-operator-system
  labels:
    cluster-api-operator: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster-api-operator: controller
  template:
    metadata:
      labels:
        cluster-api-operator: controller
    spec:
      containers:
      - name: manager
        image: registry.k8s.io/cluster-api/capi-operator:v0.10.0
        command:
        - /manager
        args:
        - --leader-elect
