apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-adapter-rook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://opendev.org/openstack/openstack-helm
    path: ceph-adapter-rook
    targetRevision: master
    helm:
      values: |
        # force Argo CD refresh
        ceph_cluster_namespace: rook-ceph
        conf:
          ceph:
            global:
              mon_host: "[v2:10.99.152.90:3300,v1:10.99.152.90:6789],[v2:10.110.116.4:3300,v1:10.110.116.4:6789]"
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
