apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: glance
  namespace: rook-ceph
spec:
  caps:
    mon: "allow r"
    osd: "allow class-read object_prefix rbd_children, allow rwx pool=images"
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: cinder
  namespace: rook-ceph
spec:
  caps:
    mon: "allow r"
    osd: "allow class-read object_prefix rbd_children, allow rwx pool=rbd"
---
apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: nova
  namespace: rook-ceph
spec:
  caps:
    mon: "allow r"
    osd: "allow class-read object_prefix rbd_children, allow rwx pool=rbd, allow rwx pool=vms"
