apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-provisioners
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm
      targetRevision: master
      path: ceph-provisioners
      helm:
        releaseName: ceph-provisioners
        valueFiles:
          - $values/cluster/argocd/openstack/values/ceph-provisioners.yaml
    - repoURL: https://github.com/daigo-suhara/capt-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
