apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://opendev.org/openstack/openstack-helm
      targetRevision: master
      path: mariadb
      helm:
        releaseName: mariadb
        valueFiles:
          - $values/cluster/argocd/openstack/values/mariadb.yaml
    - repoURL: https://github.com/daigo-suhara/capt-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
